import assert from 'node:assert/strict';
import {simulate, planOrder} from '../../public/static/js/itinerary.js';
import {state} from '../../public/static/js/state.js';
const leg = minutes=>({minutes,mode:'estimate'});
const A={identity_key:'A',start:'17:00',end:'18:30'};
const B={identity_key:'B',start:'17:00',end:'17:35'};
const matrix = new Map([['@origin|A',leg(5)],['@origin|B',leg(5)],['A|B',leg(10)],['B|A',leg(10)]]);
const options={matrix,departAt:17*60,dwell:30};
assert.equal(simulate([A,B],options).feasible,1);
const optimized=planOrder([A,B],options);
assert.equal(optimized.plan.feasible,2);
assert.deepEqual(optimized.plan.stops.map(s=>s.event.identity_key),['B','A']);
assert.equal(optimized.exhaustive,true);
assert.equal(simulate([{...A,end:'17:20'}],options).feasible,0);
assert.equal(simulate([{...A,start:null}],options).feasible,0);
const late=simulate([{...A,start:'16:00',end:'16:30'},B],options);
assert.equal(late.stops[1].arrival,17*60+15);
state.config={max_exact_stops:1};
assert.equal(planOrder([A,B],options).exhaustive,false);
console.log('Itinerary checks passed: time windows, dwell, late arrivals, exact ordering and heuristic labelling.');
